export const API_KEY = "coWPLtsaQYAhRKBnWEEOKcnnNXgKwGHDBn7vLl1c";
export const NPS_API = "https://developer.nps.gov/api/v1";

// https://www.nps.gov/aboutus/national-park-system.htm
const NAT_BATTLEFIELD_CODES = [
  "anti",
  "biho",
  "cowp",
  "fodo",
  "fone",
  "mono",
  "mocr",
  "pete",
  "stri",
  "tupe",
  "wicr",
];

const NAT_BATTLEFIELD_PARK_CODES = ["kemo", "mana", "rich", "rira"];

const NAT_MILITARY_PARK_CODES = [
  "chch",
  "frsp",
  "gett",
  "guco",
  "hobe",
  "kimo",
  "peri",
  "shil",
  "vick",
];

const NAT_PARK_CODES = [
  "acad",
  "arch",
  "badl",
  "bibe",
  "bisc",
  "blca",
  "brca",
  "cany",
  "care",
  "cave",
  "chis",
  "cong",
  "crla",
  "cuva",
  "deva",
  "dena",
  "drto",
  "ever",
  "gaar",
  "jeff",
  "glba",
  "glac",
  "grca",
  "grte",
  "grba",
  "grsa",
  "grsm",
  "gumo",
  "hale",
  "havo",
  "hosp",
  "indu",
  "isro",
  "jotr",
  "katm",
  "kefj",
  "kova",
  "lacl",
  "lavo",
  "maca",
  "meve",
  "mora",
  "npsa",
  "neri",
  "noca",
  "olym",
  "pefo",
  "pinn",
  "redw",
  "romo",
  "sagu",
  "seki",
  "shen",
  "thro",
  "viis",
  "voya",
  "whsa",
  "wica",
  "wrst",
  "yell",
  "yose",
  "zion",
];

const NAT_HISTORIC_CODES = [
  "abli",
  "adam",
  "apco",
  "blrv",
  "brvb",
  "bost",
  "cari",
  "cebe",
  "chcu",
  "choh",
  "colo",
  "cuga",
  "daav",
  "frst",
  "fosu",
  "gero",
  "gosp",
  "hafe",
  "hart",
  "hatu",
  "home",
  "hocu",
  "inde",
  "jela",
  "jica",
  "kala",
  "kaho",
  "kewe",
  "klgo",
  "lewi",
  "lowe",
  "lyjo",
  "mapr",
  "mabi",
  "malu",
  "mima",
  "morr",
  "natc",
  "nebe",
  "jazz",
  "nepe",
  "ocmu",
  "paal",
  "pagr",
  "peco",
  "puho",
  "reer",
  "rori",
  "saga",
  "saan",
  "safr",
  "sajh",
  "sara",
  "sari",
  "sitk",
  "stge",
  "edis",
  "tuma",
  "vafo",
  "wapa",
  "wefa",
  "wori",
];

const NAT_HISTORIC_SITE_CODES = [
  "alpo",
  "ande",
  "anjo",
  "beol",
  "boaf",
  "carl",
  "cawo",
  "chpi",
  "chri",
  "clba",
  "edal",
  "eise",
  "elro",
  "euon",
  "fila",
  "fobo",
  "foda",
  "fola",
  "fols",
  "foth",
  "fopo",
  "fora",
  "fosc",
  "fosm",
  "fous",
  "fova",
  "frdo",
  "frla",
  "frhi",
  "grko",
  "hamp",
  "hstr",
  "heho",
  "hofr",
  "hono",
  "hofu",
  "hutr",
  "jaga",
  "jofi",
  "jomu",
  "knri",
  "liho",
  "chsc",
  "long",
  "mawa",
  "manz",
  "mava",
  "mamc",
  "miin",
  "mimi",
  "nico",
  "nisi",
  "wicl",
  "paav",
  "puhe",
  "sahi",
  "sapa",
  "sama",
  "saju",
  "sand",
  "sair",
  "spar",
  "stea",
  "thrb",
  "thri",
  "thst",
  "tuai",
  "tuin",
  "ulsg",
  "vama",
  "waba",
  "whmi",
  "wiho",
];

const NAT_MEMORIAL_CODES = [
  "arho",
  "arpo",
  "cham",
  "coro",
  "ddem",
  "deso",
  "feha",
  "flni",
  "frde",
  "gegr",
  "hagr",
  "jofl",
  "kowa",
  "linc",
  "libo",
  "lyba",
  "mlkm",
  "moru",
  "pevi",
  "poch",
  "this",
  "thje",
  "rowi",
  "valr",
  "thko",
  "vive",
  "wrbr",
  "wwii",
  "wwim",
  "wamo",
];

const NAT_MONUMENT_CODES = [
  "afbg",
  "agfo",
  "alfl",
  "ania",
  "azru",
  "band",
  "bepa",
  "bicr",
  "bowa",
  "buis",
  "cabr",
  "cane",
  "cach",
  "cakr",
  "cavo",
  "cagr",
  "casa",
  "cacl",
  "camo",
  "cebr",
  "chyo",
  "chir",
  "colm",
  "cech",
  "crmo",
  "depo",
  "deto",
  "dino",
  "efmo",
  "elma",
  "elmo",
  "flfo",
  "fofr",
  "foma",
  "fomr",
  "fopu",
  "fost",
  "foun",
  "fobu",
  "frri",
  "fomc",
  "orca",
  "gewa",
  "gwca",
  "gicl",
  "gois",
  "grpo",
  "hafo",
  "hove",
  "jeca",
  "joda",
  "kaww",
  "labe",
  "libi",
  "memy",
  "misp",
  "moca",
  "muwo",
  "nabr",
  "nava",
  "orpi",
  "petr",
  "pisp",
  "pipe",
  "popo",
  "pull",
  "rabr",
  "ruca",
  "sapu",
  "scbl",
  "stli",
  "ston",
  "sucr",
  "tica",
  "tont",
  "tule",
  "tusk",
  "tuzi",
  "vicr",
  "waco",
  "waca",
  "wupa",
  "yuho",
];

const NAT_SEASHORE_CODES = [
  "asis",
  "cana",
  "caco",
  "caha",
  "calo",
  "cuis",
  "fiis",
  "guis",
  "pais",
  "pore",
];

const NAT_SCENIC_TRAIL_CODES = ["appa", "natt", "pohe"];

const NAT_RIVER_CODES = ["biso", "buff", "mnrr", "ozar"];

const NAT_LAKESHORE_CODES = ["apis", "piro", "slbe"];

const NAT_REC_AREAS_CODES = [
  "amis",
  "bica",
  "boha",
  "chat",
  "chic",
  "cure",
  "dewa",
  "gate",
  "gari",
  "glca",
  "goga",
  "lake",
  "lamr",
  "laro",
  "samo",
  "whis",
];

const NAT_RESERVES_CODES = ["ciro", "ebla"];

const NAT_PARKWAY_CODES = ["blri", "gwmp", "natr"];

const NAT_PRESERVES_CODES = [
  "ania",
  "bela",
  "bicy",
  "bith",
  "crmo",
  "katm",
  "lacl",
  "liri",
  "moja",
  "noat",
  "tapr",
  "timu",
  "vall",
  "wrst",
  "yuch",
];

const NAT_WILD_SCENIC_RIVER_CODES = [
  "alag",
  "blue",
  "greg",
  "lode",
  "mnrr",
  "niob",
  "obed",
  "rigr",
  "sacn",
  "upde",
];

const OTHER_DESIGNATION_CODES = [
  "cato",
  "coga",
  "fowa",
  "gree",
  "nace",
  "nama",
  "pisc",
  "prwi",
  "rocr",
  "whho",
  "wotr",
];

export const PARK_DESIGNATION_KEY = {
  NAT_PARK: "national-park",
  NAT_BATTLEFIELD: "national-battlefield",
  NAT_BATTLEFIELD_PARK: "national-battlefield-park",
  NAT_BATTLEFIELD_SITE: "national-battlefield-site",
  NAT_MILITARY_PARK: "national-military-park",
  NAT_HISTORIC_PARK: "national-historic-park",
  NAT_HISTORIC_SITE: "national-historic-site",
  NAT_LAKESHORE: "national-lakeshore",
  NAT_MEMORIAL: "national-memorial",
  NAT_MONUMENT: "national-monument",
  NAT_PARKWAY: "national-parkway",
  NAT_PRESERVES: "national-preserve",
  NAT_RESERVES: "national-reserve",
  NAT_REC_AREA: "national-recreation-area",
  NAT_RIVER: "national-river",
  NAT_SCENIC_TRAIL: "national-scenic-trail",
  NAT_SEASHORE: "national-seashore",
  NAT_WILD_AND_SCENIC_RIVER: "national-wild-and-scenic-river",
  INTERNATIONAL_HISTORIC_SITE: "international-historic-site",
  OTHER_DESIGNATION: "other-designation",
};

export const LIST_OPTIONS = [...Object.values(PARK_DESIGNATION_KEY)];

export const PARK_CODES = {
  [PARK_DESIGNATION_KEY.NAT_PARK]: NAT_PARK_CODES,
  [PARK_DESIGNATION_KEY.NAT_BATTLEFIELD]: NAT_BATTLEFIELD_CODES,
  [PARK_DESIGNATION_KEY.NAT_BATTLEFIELD_PARK]: NAT_BATTLEFIELD_PARK_CODES,
  [PARK_DESIGNATION_KEY.NAT_BATTLEFIELD_SITE]: ["brcr"],
  [PARK_DESIGNATION_KEY.NAT_MILITARY_PARK]: NAT_MILITARY_PARK_CODES,
  [PARK_DESIGNATION_KEY.NAT_HISTORIC_PARK]: NAT_HISTORIC_CODES,
  [PARK_DESIGNATION_KEY.NAT_HISTORIC_SITE]: NAT_HISTORIC_SITE_CODES,
  [PARK_DESIGNATION_KEY.NAT_MEMORIAL]: NAT_MEMORIAL_CODES,
  [PARK_DESIGNATION_KEY.NAT_MONUMENT]: NAT_MONUMENT_CODES,
  [PARK_DESIGNATION_KEY.NAT_SEASHORE]: NAT_SEASHORE_CODES,
  [PARK_DESIGNATION_KEY.NAT_SCENIC_TRAIL]: NAT_SCENIC_TRAIL_CODES,
  [PARK_DESIGNATION_KEY.NAT_REC_AREA]: NAT_REC_AREAS_CODES,
  [PARK_DESIGNATION_KEY.NAT_RIVER]: NAT_RIVER_CODES,
  [PARK_DESIGNATION_KEY.NAT_LAKESHORE]: NAT_LAKESHORE_CODES,
  [PARK_DESIGNATION_KEY.NAT_PARKWAY]: NAT_PARKWAY_CODES,
  [PARK_DESIGNATION_KEY.NAT_RESERVES]: NAT_RESERVES_CODES,
  [PARK_DESIGNATION_KEY.NAT_PRESERVES]: NAT_PRESERVES_CODES,
  [PARK_DESIGNATION_KEY.NAT_WILD_AND_SCENIC_RIVER]: NAT_WILD_SCENIC_RIVER_CODES,
  [PARK_DESIGNATION_KEY.OTHER_DESIGNATION]: OTHER_DESIGNATION_CODES,
  [PARK_DESIGNATION_KEY.INTERNATIONAL_HISTORIC_SITE]: ["sacr"],
};

const generateId = () =>
  Math.floor(1000000000 + Math.random() * 9000).toString();

export const FORMATTED_PARKS = {
  [PARK_DESIGNATION_KEY.NAT_MEMORIAL]: [
    {
      id: generateId(),
      images: [
        {
          altText: "Fort gate",
          url: "https://www.nps.gov/common/uploads/structured_data/3C7B5019-1DD8-B71B-0B8694BFD33E8B3C.jpg",
        },
      ],
      name: "Fort Caroline National Memorial",
      fullName: "Fort Caroline National Memorial",
      states: "FL",
      latitude: "30.47251894",
      longitude: "-81.49950104",
      designation: "Ecological & Historic Preserve",
      url: "https://www.nps.gov/timu/learn/historyculture/foca.htm",
    },
  ],
  [PARK_DESIGNATION_KEY.NAT_MONUMENT]: [
    {
      id: generateId(),
      images: [],
      name: "Hohokam Pima National Monument",
      fullName: "Hohokam Pima National Monument",
      states: "AZ",
      latitude: "32.192890",
      longitude: "-112.925960",
      designation: "National Monument",
      url: "https://www.nationalparks.org/explore/parks/hohokam-pima-national-monument",
    },
  ],
  [PARK_DESIGNATION_KEY.NAT_PARK]: [
    {
      id: generateId(),
      images: [
        {
          altText:
            "A deep canyon with a forested floor and steep granite cliffs",
          url: "https://www.nps.gov/common/uploads/structured_data/3C7A250B-1DD8-B71B-0BCF61A89A8B2970.jpg",
        },
      ],
      name: "Kings Canyon National Park",
      fullName: "Kings Canyon National Park",
      states: "CA",
      latitude: "36.739991",
      longitude: "-118.963389",
      designation: "National Parks",
      url: "https://www.nps.gov/seki/index.htm",
    },
  ],
  [PARK_DESIGNATION_KEY.NAT_PRESERVES]: [
    {
      id: generateId(),
      images: [
        {
          altText: "Three brown bears walking along a dirt road",
          url: "https://www.nps.gov/common/uploads/structured_data/FC8ECC8C-A531-46F8-0D60DF1C84105DBE.jpg",
        },
      ],
      name: "Denali National Preserve",
      fullName: "Denali National Preserve",
      states: "AK",
      latitude: "63.29777484",
      longitude: "-151.0526568",
      designation: "National Park & Preserve",
      url: "https://www.nps.gov/dena/index.htm",
    },
    {
      id: generateId(),
      images: [
        {
          altText: "Alpenglow on the granite cliffs of mountains",
          url: "https://www.nps.gov/common/uploads/structured_data/3C7A89F4-1DD8-B71B-0B52204A2EBF61A4.jpg",
        },
      ],
      name: "Gates of the Arctic National Preserve",
      fullName: "Gates of the Arctic National Preserve",
      states: "AK",
      latitude: "67.75961636",
      longitude: "-153.2917758",
      designation: "National Park & Preserve",
      url: "https://www.nps.gov/glba/index.htm",
    },
    {
      id: generateId(),
      images: [
        {
          altText:
            "Icebergs, calved from tidewater glaciers are a common sight in Glacier Bay National Park.",
          url: "https://www.nps.gov/common/uploads/structured_data/3C790BBF-1DD8-B71B-0B0AE92D0B9C24EB.jpg",
        },
      ],
      name: "Glacier Bay National Preserve",
      fullName: "Glacier Bay National Preserve",
      states: "AK",
      latitude: "58.80086718",
      longitude: "-136.8407579",
      designation: "National Park & Preserve",
      url: "https://www.nps.gov/glba/index.htm",
    },
    {
      id: generateId(),
      images: [
        {
          altText: "Grasslands, large dunes, and snow-capped peaks at sunset",
          url: "https://www.nps.gov/common/uploads/structured_data/BC4ACB4C-0A6D-0188-E9A6AA1217827461.jpg",
        },
      ],
      name: "Great Sand Dunes National Preserve",
      fullName: "Great Sand Dunes National Preserve",
      states: "CO",
      latitude: "37.79256812",
      longitude: "-105.5919572",
      designation: "National Park & Preserve",
      url: "https://www.nps.gov/grsa/index.htm",
    },
  ],
  [PARK_DESIGNATION_KEY.NAT_PARKWAY]: [
    {
      id: generateId(),
      images: [
        {
          altText: "Winter sunrise on snow-covered Teton Range",
          url: "https://www.nps.gov/common/uploads/structured_data/3C7FA7B7-1DD8-B71B-0B7B45B73D1C90C3.jpg",
        },
      ],
      name: "John D. Rockefeller, Jr. Memorial Parkway",
      fullName: "John D. Rockefeller, Jr. Memorial Parkway",
      states: "WY",
      latitude: "43.81853565",
      longitude: "-110.7054666",
      designation: "Memorial Parkway",
      url: "https://www.nps.gov/grte/planyourvisit/jodr.htm",
    },
  ],
  [PARK_DESIGNATION_KEY.NAT_REC_AREA]: [
    {
      id: generateId(),
      images: [
        {
          altText: "boats on the water with mountains and trees surrounding",
          url: "https://www.nps.gov/common/uploads/structured_data/3C7A599D-1DD8-B71B-0BBDC12BEC5107B5.jpg",
        },
      ],
      name: "Lake Chelan National Recreation",
      fullName: "Lake Chelan National Recreation",
      states: "WA",
      latitude: "48.026974",
      longitude: "-120.337732",
      designation: "National Recreation Area",
      url: "https://www.nps.gov/noca/planyourvisit/visitorcenters.htm",
    },
    {
      id: generateId(),
      images: [
        {
          altText: "Tents set up in a wooded area.",
          url: "https://www.nps.gov/common/uploads/structured_data/3C7A5B0D-1DD8-B71B-0B1104A95B7A2026.jpg",
        },
      ],
      name: "Lake Ross National Recreation",
      fullName: "Lake Ross National Recreation",
      states: "WA",
      latitude: "48.868113",
      longitude: "-121.06395",
      designation: "National Recreation Area",
      url: "https://www.nps.gov/noca/planyourvisit/visitorcenters.htm",
    },
  ],
};
